### PR TITLE
Updated to build with GHC 7.10, and added some documentation

### PR DESCRIPTION
**Pull request by Hodapp87**
1. Atom required some updates to build with GHC 7.10 (mainly from Functor-Applicative-Monad change), so I made this change in some earlier commits.
2. In addition I added some missing documentation, and restructured the imports in Atom.hs so that Haddock puts it all on a single page, as it's a bit tiresome to otherwise have to refer to 5 or 6 individual module pages.
3. Some entire modules existed, commented out, and I have split these out again into separate modules and made them build again.

### CODE REVIEW

**Comment by leepike** [comment]
Wow, thanks @Hodapp87 !

**Comment by Hodapp87** [comment]
Welcome!

I have been using this code a bit at my day job, and it seems to be some considerable work that would see the light of day more if it had better docs and examples. I may try to get some better examples into it too soon; might you be able to update the Hackage package once I do?

**Comment by leepike** [comment]
@Hodapp87 that is awesome! I'd be happy to integrate examples and update Hackage.

**Comment by Hodapp87** [comment]
Great. I will try to get some functioning examples in there soon.

**Pull request merged**
